package utils

import (
	"fmt"
	"strings"
)

type BirthElement struct {
	Flower   string `json:"flower"`
	FlowerEN string `json:"flower_en"`
	Stone    string `json:"stone"`
	Meaning  string `json:"meaning"`
}

type FlowerDetail struct {
	Flower   string
	FlowerEN string
	Meaning  string
}

// GetBirthElements returns flower, stone and meaning based on the date
func GetBirthElements(month, day int) BirthElement {
	stones := map[int]string{
		1: "가넷 (석류석)", 2: "자수정", 3: "아쿠아마린", 4: "다이아몬드",
		5: "에메랄드", 6: "진주", 7: "루비", 8: "페리도트",
		9: "사파이어", 10: "오팔", 11: "토파즈", 12: "터키석",
	}

	detail := getDailyFlower(month, day)

	return BirthElement{
		Flower:   detail.Flower,
		FlowerEN: detail.FlowerEN,
		Stone:    stones[month],
		Meaning:  detail.Meaning,
	}
}

func getDailyFlower(month, day int) FlowerDetail {
	key := fmt.Sprintf("%d-%d", month, day)
	if val, ok := dailyFlowers[key]; ok {
		return val
	}
	return FlowerDetail{Flower: "알 수 없는 꽃", FlowerEN: "Unknown Flower", Meaning: "행복"}
}

// GetMonthName returns the English name of the month for Wikipedia API
func GetMonthName(month int) string {
	names := []string{
		"January", "February", "March", "April", "May", "June",
		"July", "August", "September", "October", "November", "December",
	}
	if month < 1 || month > 12 {
		return "January"
	}
	return names[month-1]
}

// GenerateAIPrompt creates a creative prompt for image generation reflecting all birth elements
func GenerateAIPrompt(animal, color, starSign, flowerEN, meaning, stone string) string {
	animalEN := map[string]string{
		"쥐": "rat", "소": "ox", "호랑이": "tiger", "토끼": "rabbit",
		"용": "dragon", "뱀": "snake", "말": "horse", "양": "sheep",
		"원숭이": "monkey", "닭": "rooster", "개": "dog", "돼지": "pig",
	}[animal]

	colorEN := map[string]string{
		"청": "blue", "적": "red", "황": "gold", "백": "white", "흑": "black",
	}[color]

	stoneEN := "gemstone"
	stonesMap := map[string]string{
		"가넷": "Garnet", "자수정": "Amethyst", "아쿠아마린": "Aquamarine", "다이아몬드": "Diamond",
		"에메랄드": "Emerald", "진주": "Pearl", "루비": "Ruby", "페리도트": "Peridot",
		"사파이어": "Sapphire", "오팔": "Opal", "토파즈": "Topaz", "터키석": "Turquoise",
	}
	for ko, en := range stonesMap {
		if strings.Contains(stone, ko) {
			stoneEN = en
			break
		}
	}

	if animalEN == "" {
		animalEN = animal
	}
	if colorEN == "" {
		colorEN = color
	}

	return fmt.Sprintf("A breathtaking cinematic masterpiece of a %s %s, embodying the spirit of '%s', surrounded by a lush field of blooming %s. Nearby, a sacred %s crystal radiates a mystical glow. Above, the %s constellation shimmers in a starlit cosmic nebula sky. Ethereal atmosphere, magical particles, hyper-realistic, 8k resolution, vibrant and divine lighting.",
		colorEN, animalEN, meaning, flowerEN, stoneEN, starSign)
}

var dailyFlowers = map[string]FlowerDetail{
	"1-1":   {"스노드롭", "Snow Drop", "희망"},
	"1-2":   {"노랑수선화", "Narcissus Jonquilla", "사랑에 답하여"},
	"1-3":   {"샤프란", "Spring Crocus", "후회 없는 청춘"},
	"1-4":   {"히아신스", "Hyacinth", "차분한"},
	"1-5":   {"노루귀", "Hepatica", "인내"},
	"1-6":   {"흰제비꽃", "white violet", "순진무구한 사랑"},
	"1-7":   {"튤립", "Tulipa", "실연"},
	"1-8":   {"보랏빛 제비꽃", "purple violet", "사랑"},
	"1-9":   {"노랑 제비꽃", "yellow violet", "수줍은 사랑"},
	"1-10":  {"회양목", "Box-Tree", "참고 견뎌냄"},
	"1-11":  {"측백나무", "Arborvitae", "견고한 우정"},
	"1-12":  {"스위트 알리섬", "Sweet Alyssum", "빼어난 미모"},
	"1-13":  {"수선화", "Narcissus", "신비"},
	"1-14":  {"시클라멘", "Cyclamen", "내성적 성격"},
	"1-15":  {"가시", "Thorn", "엄격"},
	"1-16":  {"노랑 히아신스", "yellow Hyacinth", "승부"},
	"1-17":  {"수영", "Rumex", "친근한 정"},
	"1-18":  {"어저귀", "Indian Mallow", "억측"},
	"1-19":  {"소나무", "Pine", "불로장수"},
	"1-20":  {"미나리아재비", "Butter Cup", "천진난만"},
	"1-21":  {"담쟁이덩굴", "Ivy", "우정"},
	"1-22":  {"이끼", "Moss", "모성애"},
	"1-23":  {"부들", "Bullrush", "순종"},
	"1-24":  {"가을에 피는 샤프란", "Saffron-Crocus", "절도의 미"},
	"1-25":  {"점나도나물", "Cerastium", "순진"},
	"1-26":  {"미모사", "Humble Plant", "예민한 마음"},
	"1-27":  {"마가목", "Sorbus", "게으름을 모르는 마음"},
	"1-28":  {"검은 포플라", "Black Poplar", "용기"},
	"1-29":  {"이끼", "Moss", "모성애"},
	"1-30":  {"매쉬 메리골드", "Mash Marigold", "반드시 오고야 말 행복"},
	"1-31":  {"노란 사프란", "yellow Spring-Crocus", "청춘의 환희"},
	"2-1":   {"앵초", "Primrose", "젊은 시절의 고뇌"},
	"2-2":   {"모과", "Chaendmeles", "평범"},
	"2-3":   {"황새냉이", "Cardamine", "그대에게 바친다"},
	"2-4":   {"빨간앵초", "Primrose", "돌보지 않는 아름다움"},
	"2-5":   {"양치식물", "Fern", "사랑스러움"},
	"2-6":   {"바위솔", "Horse-Leek", "가사에 근면함"},
	"2-7":   {"물망초", "Forget-me-not", "날 잊지 말아요"},
	"2-8":   {"범의귀", "Saxifrage", "절실한 애정"},
	"2-9":   {"은매화", "Myrtle", "사랑의 속삭임"},
	"2-10":  {"서향", "Winter Daphne", "영광"},
	"2-11":  {"멜리사", "Balm", "동정"},
	"2-12":  {"쥐꼬리망초", "Justicia Procumbes", "가련미의 극치"},
	"2-13":  {"갈풀", "Canary Grass", "끈기"},
	"2-14":  {"캐모마일", "Chamomile", "역경에 굴하지 않는 강인함"},
	"2-15":  {"삼나무", "Cedar", "그대를 위해 살다"},
	"2-16":  {"월계수", "Victor's Laurel", "나무: 승리, 영광"},
	"2-17":  {"야생화", "Wild Flower", "친숙한 자연"},
	"2-18":  {"미나리아재비", "Butter Cup", "천진난만"},
	"2-19":  {"떡갈나무", "Oak", "붙임성이 좋음"},
	"2-20":  {"칼미아", "Kalmia", "커다란 희망"},
	"2-21":  {"네모필라", "California Blue-bell", "애국심"},
	"2-22":  {"무궁화", "Rose of Sharon", "미묘한 아름다움"},
	"2-23":  {"살구꽃", "Prunus", "아가씨의 수줍음"},
	"2-24":  {"빙카", "Periwinkle", "즐거운 추억"},
	"2-25":  {"사향장미", "Musk Rose", "변덕스런 사랑"},
	"2-26":  {"아도니스(붉은색)", "Adonis", "추억"},
	"2-27":  {"아라비아의 별", "Star of Arabia", "순수"},
	"2-28":  {"보리", "Straw", "일치단결"},
	"2-29":  {"아르메리아", "Armeria", "배려"},
	"3-1":   {"수선화", "Narcissus", "자존"},
	"3-2":   {"미나리아재비", "Butter Cup", "아름다운 인격"},
	"3-3":   {"자운영", "Astraglus", "나의 행복"},
	"3-4":   {"나무딸기", "Raspberry", "애정"},
	"3-5":   {"수레국화", "Corn Flower", "행복감"},
	"3-6":   {"데이지", "Daisy", "명랑"},
	"3-7":   {"황새냉이", "Cardamine", "사무치는 그리움"},
	"3-8":   {"밤꽃", "Castanea", "진심"},
	"3-9":   {"낙엽송", "Larch", "대담"},
	"3-10":  {"느릅나무", "Hackberry", "고귀함"},
	"3-11":  {"씀바귀", "lxeris", "순박함"},
	"3-12":  {"수양버들", "Weeping Willow", "사랑의 슬픔"},
	"3-13":  {"옥잠화", "Daylily", "사랑의 망각"},
	"3-14":  {"아몬드", "Almond", "희망"},
	"3-15":  {"독당근", "Conium Maculatum", "죽음도 아깝지 않음"},
	"3-16":  {"박하", "Mint", "미덕"},
	"3-17":  {"콩꽃", "Beans", "반드시 오고야 말 행복"},
	"3-18":  {"아스파라거스", "Asparagus", "무변화"},
	"3-19":  {"치자나무", "Cape Jasmine", "한없는 즐거움"},
	"3-20":  {"보라색 튤립", "Tulipa", "영원한 애정"},
	"3-21":  {"벚꽃난", "Honey-Plant", "인생의 출발"},
	"3-22":  {"당아욱", "Mallow", "은혜"},
	"3-23":  {"글라디올러스", "Gladiolus", "정열적인 사랑"},
	"3-24":  {"금영화", "Califonia Poppy", "희망"},
	"3-25":  {"덩굴성 식물", "Climbing Plant", "아름다움"},
	"3-26":  {"흰앵초", "Primrose", "첫사랑"},
	"3-27":  {"칼세올라리아", "Calceolaria", "도움"},
	"3-28":  {"꽃아카시아나무", "Robinia Hispida", "품위"},
	"3-29":  {"우엉", "Arctium", "괴롭히지 말아요"},
	"3-30":  {"금작화", "Broom", "청초"},
	"3-31":  {"니겔라", "Nigella Damascena", "꿈길의 애정"},
	"4-1":   {"아몬드", "Almond", "진실한 사랑"},
	"4-2":   {"아네모네", "Wind Flower", "기대"},
	"4-3":   {"나팔수선화", "Daffodil", "존경"},
	"4-4":   {"빨간 아네모네", "Wind Flower", "그대를 사랑해"},
	"4-5":   {"무화과", "Fig-Tree", "풍부"},
	"4-6":   {"아도니스(노란색)", "Adonis", "영원한 행복"},
	"4-7":   {"공작고사리", "Adiantum", "신명"},
	"4-8":   {"금작화", "Broom", "박애"},
	"4-9":   {"벚나무", "Cherry", "정신미, 거짓말"},
	"4-10":  {"빙카", "Periwinkle", "즐거운 추억"},
	"4-11":  {"꽃고비", "Blemonium Coeruleum", "와주세요"},
	"4-12":  {"복사꽃", "Peach", "사랑의 노예"},
	"4-13":  {"페르시아 국화", "Golden Wave", "경쟁심"},
	"4-14":  {"흰나팔꽃", "Morning-Glory", "넘치는 기쁨"},
	"4-15":  {"펜 오키드", "Fen Orchid", "훌륭함"},
	"4-16":  {"튤립", "Tulipa", "아름다운 눈동자"},
	"4-17":  {"독일 창포", "German Iris", "멋진 결혼"},
	"4-18":  {"자운영", "Astragalus", "그대의 관대한 사랑"},
	"4-19":  {"참제비고깔", "Larkspur", "청명"},
	"4-20":  {"배나무", "Pear", "온화한 애정"},
	"4-21":  {"수양버들", "Weeping Willow", "내 가슴의 슬픔"},
	"4-22":  {"과꽃", "China Aster", "믿음직한 사랑"},
	"4-23":  {"도라지", "Balloom-Flower", "상냥하고 따뜻함"},
	"4-24":  {"제라늄", "Geranium", "결실"},
	"4-25":  {"중국 패모", "Gritillaria Thunbergii", "위엄"},
	"4-26":  {"논냉이", "Cardamine Iyrata", "불타는 애정"},
	"4-27":  {"수련", "Water Lily", "청순한 마음"},
	"4-28":  {"설앵초", "Primrose", "비할 바 없는 아름다움"},
	"4-29":  {"동백나무", "Camellia", "매력"},
	"4-30":  {"금사슬나무", "Golden-Chain", "슬픈 아름다움"},
	"5-1":   {"황화구륜초", "Cowslip", "젊은 날의 슬픔"},
	"5-2":   {"미나리아재비", "Butter Cup", "천진난만함"},
	"5-3":   {"민들레", "Dandelion", "신탁"},
	"5-4":   {"딸기", "Strawberry", "존중과 애정"},
	"5-5":   {"은방울꽃", "May lily", "섬세함"},
	"5-6":   {"비단향나무꽃", "Stock", "영원한 아름다움"},
	"5-7":   {"딸기", "Strawberry", "사랑과 존경"},
	"5-8":   {"수련", "Water Lily", "청순한 마음"},
	"5-9":   {"겹벚꽃", "Prunus", "정숙, 단아함, 절세의 미인"},
	"5-10":  {"꽃창포", "Flag Iris", "우아한 마음"},
	"5-11":  {"사과", "Apple", "유혹"},
	"5-12":  {"라일락", "Lilac", "사랑의 싹"},
	"5-13":  {"산사나무", "Hawthorn", "유일한 사랑"},
	"5-14":  {"매발톱꽃", "Columbine", "승리의 맹세"},
	"5-15":  {"물망초", "Forget-me-not", "나를 잊지 말아요"},
	"5-16":  {"조밥나물", "Hieracium", "선언"},
	"5-17":  {"노랑 튤립", "Tulipa", "사랑의 표시"},
	"5-18":  {"옥슬립 앵초", "Oxlip", "첫사랑"},
	"5-19":  {"아리스타타", "Aristata", "아름다움의 소유자"},
	"5-20":  {"괭이밥", "Wood Sorrel", "빛나는 마음"},
	"5-21":  {"담홍색 참제비고깔", "Larkspur", "자유"},
	"5-22":  {"귀고리꽃", "Ear Drops", "열렬한 마음"},
	"5-23":  {"풀의 싹", "Leaf Buds", "첫사랑의 추억"},
	"5-24":  {"헬리오 트로프", "Heliotropium", "사랑이여 영원하라"},
	"5-25":  {"삼색제비꽃", "Pansy", "순애"},
	"5-26":  {"올리브나무", "Olive", "평화"},
	"5-27":  {"데이지", "Daisy", "순수한 마음"},
	"5-28":  {"박하", "Mint", "미덕, 다시 한번 더 사랑하고 싶습니다"},
	"5-29":  {"토끼풀", "Clover", "쾌활"},
	"5-30":  {"보랏빛 라일락", "Lilac", "사랑의 싹이 트다"},
	"5-31":  {"무릇", "Scilla", "강한 자제력"},
	"6-1":   {"연분홍 장미", "Maiden Blush Rose", "나의 마음 그대만이 아네"},
	"6-2":   {"빨강 매발톱꽃", "Columbine", "솔직"},
	"6-3":   {"아마", "Plax", "감사"},
	"6-4":   {"장미", "Damaskrose", "아름답게 빛나는 얼굴 모습"},
	"6-5":   {"메리골드", "Marigold", "이별의 슬픔, 가련한 애정"},
	"6-6":   {"노랑 붓꽃", "Yellow Water Flag", "믿는 자의 행복"},
	"6-7":   {"슈미트티아나", "Schmidtiana", "사모하는 마음"},
	"6-8":   {"재스민", "Jasmine", "사랑스러움"},
	"6-9":   {"스위트피", "Sweet Pea", "우아한 추억"},
	"6-10":  {"수염패랭이꽃", "Sweet William", "의협심"},
	"6-11":  {"중국패모", "Fritillaria Thunbergii", "위엄"},
	"6-12":  {"레제다 오도라타", "Reseda Odorata", "매력"},
	"6-13":  {"디기탈리스", "Fox Glove", "가슴 속의 생각"},
	"6-14":  {"뚜껑별꽃", "Anagallis", "추상"},
	"6-15":  {"카네이션", "Carnation", "정열"},
	"6-16":  {"튜베 로즈", "Tube Rose", "위험한 쾌락"},
	"6-17":  {"토끼풀", "Clover", "감화"},
	"6-18":  {"백리향", "Thyme", "용기"},
	"6-19":  {"장미", "Sweet Brier", "사랑"},
	"6-20":  {"꼬리풀", "Speedwell", "달성"},
	"6-21":  {"달맞이꽃", "Evening Primrose", "자유스러운 마음"},
	"6-22":  {"가막살나무", "Viburnum", "사랑은 죽음보다 강하다"},
	"6-23":  {"접시꽃", "Holly Hock", "열렬한 연애"},
	"6-24":  {"버베나", "Garden Verbena", "가족의 화합"},
	"6-25":  {"나팔꽃", "Morning Glory", "덧없는 사랑"},
	"6-26":  {"흰 라일락", "Lilac", "아름다운 맹세"},
	"6-27":  {"시계꽃", "Passion Flower", "성스러운 사랑"},
	"6-28":  {"제라늄", "Geranium", "그대가 있기에 행복이 있네"},
	"6-29":  {"빨강 제라늄", "Geranium", "그대가 있어 사랑이 있네"},
	"6-30":  {"인동", "Honey Suckle", "사랑의 인연"},
	"7-1":   {"단양쑥부쟁이", "Fig Marigold", "태만"},
	"7-2":   {"금어초", "Snap Dragon", "욕망"},
	"7-3":   {"흰색 양귀비", "Papaver", "망각"},
	"7-4":   {"자목련", "Lily Magnolia", "자연애"},
	"7-5":   {"라벤더", "Lavender", "풍부한 향기"},
	"7-6":   {"해바라기", "Sun Flower", "애모"},
	"7-7":   {"까치밥나무", "Goose Berry", "예상"},
	"7-8":   {"열엽모간", "Ranunculus pedatifidus", "다시 만날 날까지"},
	"7-9":   {"아이비 제라늄", "Ivyleaved Geranium", "진실한 애정"},
	"7-10":  {"초롱꽃", "Canterbury Bells", "감사"},
	"7-11":  {"아스포델", "Asphodel", "나는 당신의 것"},
	"7-12":  {"좁은입배풍동", "Solanum", "참을 수 없어"},
	"7-13":  {"잡초의 꽃", "Flower of Grass", "실제적인 사람"},
	"7-14":  {"플록스", "Phlox", "온화"},
	"7-15":  {"들장미", "Austrian Briar Rose", "사랑스러움"},
	"7-16":  {"비단향꽃무", "Stock", "영원한 아름다움"},
	"7-17":  {"흰색장미", "White Rose", "존경"},
	"7-18":  {"이끼 장미", "Moss Rose", "가련함"},
	"7-19":  {"백부자", "Aconite", "아름답게 빛나다"},
	"7-20":  {"가지", "Egg Plant", "진실"},
	"7-21":  {"노랑장미", "Yellow Rose", "아름다움"},
	"7-22":  {"패랭이꽃", "Superb Pink", "사모"},
	"7-23":  {"장미", "York & Lancaster Rose", "아름다움"},
	"7-24":  {"연령초", "Trillum", "그윽한 마음"},
	"7-25":  {"말오줌나무", "Elder-Tree", "열심"},
	"7-26":  {"향쑥", "Wormwood", "평화"},
	"7-27":  {"제라늄", "Geranium", "진실한 애정"},
	"7-28":  {"패랭이꽃", "Dianthos Superbus", "언제나 사랑"},
	"7-29":  {"선인장", "Cactus", "불타는 마음"},
	"7-30":  {"서양종 보리수", "Lime Tree, Linden", "부부애"},
	"7-31":  {"호박", "Pumpkin", "광대함"},
	"8-1":   {"빨강 양귀비", "Papaver", "위로"},
	"8-2":   {"수레국화", "Corn Flower", "행복"},
	"8-3":   {"수박풀", "Flower of an Hour", "아가씨의 아름다운 자태"},
	"8-4":   {"옥수수", "Corn", "재보"},
	"8-5":   {"에리카", "Heath", "고독"},
	"8-6":   {"능소화", "Trumpet Flower", "명예"},
	"8-7":   {"석류", "Pomegranate", "완숙한 아름다움"},
	"8-8":   {"진달래", "Azalea", "사랑의 희열"},
	"8-9":   {"시스터스", "Cistus", "인기"},
	"8-10":  {"이끼", "Moss", "모성애"},
	"8-11":  {"빨강무늬제라늄", "Geranium Zonal", "위안"},
	"8-12":  {"협죽도", "Oleander", "위험"},
	"8-13":  {"골든 로드", "Golden Rod", "경계"},
	"8-14":  {"저먼더", "Wall Germander", "경애"},
	"8-15":  {"해바라기", "Sun Flower", "광휘"},
	"8-16":  {"타마린드", "Tamarindus", "사치"},
	"8-17":  {"튤립나무", "Tulip-Tree", "전원의 행복"},
	"8-18":  {"접시꽃", "Holly Hock", "열렬한 사랑"},
	"8-19":  {"로사 캠피온", "Rosa Campion", "성실"},
	"8-20":  {"프리지아", "Freesia", "순진, 천진난만"},
	"8-21":  {"짚신나물", "Agrimony", "감사"},
	"8-22":  {"스피리아", "Spirea", "노력"},
	"8-23":  {"서양종 보리수", "Lime Tree, Linden", "부부애"},
	"8-24":  {"금잔화", "Calendula", "이별의 슬픔"},
	"8-25":  {"안스륨", "Flaming Flower", "사랑에 번민하는 마음"},
	"8-26":  {"하이포시스 오리어", "Hypoxis Aurea", "빛을 찾다"},
	"8-27":  {"고비", "Osumunda", "몽상"},
	"8-28":  {"에린지움", "Eryngium", "비밀스런 애정"},
	"8-29":  {"꽃담배", "Flowering Tobacco Plant", "그대가 있어서 외롭지 않네"},
	"8-30":  {"저먼더", "Wall Germander", "담백"},
	"8-31":  {"토끼풀", "Clover", "약속"},
	"9-1":   {"호랑이꽃", "Tiger Flower", "나를 사랑해 주세요"},
	"9-2":   {"멕시칸 아이비", "Cobaea", "변화"},
	"9-3":   {"마거리트", "Marguerite", "마음속에 감춘 사랑"},
	"9-4":   {"뱀무", "Geum", "만족된 사랑"},
	"9-5":   {"느릅나무", "Elm", "신뢰"},
	"9-6":   {"한련", "Nasturtium", "애국심"},
	"9-7":   {"오렌지", "Orange", "새색시의 기쁨"},
	"9-8":   {"갓", "Mustard", "무관심"},
	"9-9":   {"갓개매취", "Michaelmas Daisy", "추억"},
	"9-10":  {"흰색 과꽃", "China Aster", "믿는 마음"},
	"9-11":  {"알로에", "Aloe", "꽃도 잎새도"},
	"9-12":  {"클레마티스", "Clematis", "마음의 아름다움"},
	"9-13":  {"버드나무", "Weeping Willow", "솔직"},
	"9-14":  {"마르멜루", "Quince", "유혹"},
	"9-15":  {"다알리아", "Dahlia", "화려함"},
	"9-16":  {"용담", "Gentina", "슬픈 그대가 좋아"},
	"9-17":  {"에리카", "Heath", "고독"},
	"9-18":  {"엉겅퀴", "Thistle", "엄격"},
	"9-19":  {"사초", "Carex", "자중"},
	"9-20":  {"로즈메리", "Rosemary", "나를 생각해요"},
	"9-21":  {"사프란", "Autumn Crocus", "후회없는 청춘"},
	"9-22":  {"퀘이킹 그라스", "Quaking Grass", "흥분"},
	"9-23":  {"주목", "Yew Tree", "고상함"},
	"9-24":  {"오렌지", "Orange", "새색시의 기쁨"},
	"9-25":  {"메귀리", "Animated Oat", "음악을 좋아함"},
	"9-26":  {"감", "Date Plum", "자연미"},
	"9-27":  {"떡갈나무", "Oak", "사랑은 영원히"},
	"9-28":  {"색비름", "Love-Lies a Bleeding", "애정"},
	"9-29":  {"사과", "Apple", "명성"},
	"9-30":  {"삼나무", "Cedar", "웅대"},
	"10-1":  {"빨강 국화", "Chrysanthemum", "사랑"},
	"10-2":  {"살구", "Apricot", "아가씨의 수줍음"},
	"10-3":  {"단풍나무", "Maple", "자제"},
	"10-4":  {"홉", "Common Hop", "순진무구"},
	"10-5":  {"종려나무", "Windmill Palm", "승리"},
	"10-6":  {"개암나무", "Hazel", "화해"},
	"10-7":  {"전나무", "Fir", "고상함"},
	"10-8":  {"파슬리", "Parsley", "승리"},
	"10-9":  {"회향", "Fennel", "극찬"},
	"10-10": {"멜론", "Melon", "포식"},
	"10-11": {"부처꽃", "Lythrum", "사랑의 슬픔"},
	"10-12": {"월귤", "Bilberry", "반항심"},
	"10-13": {"조팝나무", "Spirea", "단정한 사랑"},
	"10-14": {"흰색 국화", "Chrysanthemum", "진실"},
	"10-15": {"스위트 바질", "Sweet Basil", "좋은 희망"},
	"10-16": {"채송화", "Moss Rose", "순진무구"},
	"10-17": {"포도", "Grape", "신뢰"},
	"10-18": {"넌출월귤", "Cranberry", "마음의 고통을 위로하다"},
	"10-19": {"빨강 봉선화", "Balsam", "날 건드리지 마세요"},
	"10-20": {"마", "Indian Hemp", "운명"},
	"10-21": {"엉겅퀴", "Thistle", "독립"},
	"10-22": {"벗풀", "Arrow-Head", "신뢰"},
	"10-23": {"흰독말풀", "Thorn Apple", "경애"},
	"10-24": {"매화", "Prunus Mume", "고결한 마음"},
	"10-25": {"단풍나무", "Aceracede", "염려"},
	"10-26": {"수영", "Rumex", "애정"},
	"10-27": {"들장미", "Briar Rose", "시"},
	"10-28": {"무궁화", "Rose of Sharon", "미묘한 아름다움"},
	"10-29": {"해당화", "Rosa rugosa", "이끄시는 대로"},
	"10-30": {"로벨리아", "Lobelia", "악의"},
	"10-31": {"칼라", "Calla", "열혈"},
	"11-1":  {"양모과", "Medlar", "유일한 사랑"},
	"11-2":  {"루피너스", "Lupinus", "모성애"},
	"11-3":  {"브리오니아", "Bryonia", "거절"},
	"11-4":  {"골고사리", "Hart's-Tongue Fern", "진실의 위안"},
	"11-5":  {"단양쑥부쟁이", "Fig Marigold", "공훈"},
	"11-6":  {"등골나물", "Agrimony Eupatoire", "주저"},
	"11-7":  {"메리골드", "Marigold", "이별의 슬픔"},
	"11-8":  {"가는동자꽃", "Lychnis Flos-Cuculi", "기지"},
	"11-9":  {"몰약의 꽃", "Myrrh", "진실"},
	"11-10": {"부용", "Hibiscus Mutabilis", "섬세한 아름다움"},
	"11-11": {"흰동백", "Camellia", "비밀스런 사랑"},
	"11-12": {"레몬", "Lemon", "진심으로 사모함"},
	"11-13": {"레몬 버베나", "Lemon Verbena", "인내"},
	"11-14": {"소나무", "Pine", "불로장생"},
	"11-15": {"황금싸리", "Crown Vetch", "겸손"},
	"11-16": {"크리스마스 로즈", "Christmas Rose", "추억"},
	"11-17": {"머위", "Sweet-Scented Tussilage", "공평"},
	"11-18": {"산나리", "Hill Lily", "순결"},
	"11-19": {"범의귀", "Aaron's Beard", "비밀"},
	"11-20": {"뷰글라스", "Bugloss", "진실"},
	"11-21": {"초롱꽃", "Campanula", "성실"},
	"11-22": {"매자나무", "Berberis", "까다로움"},
	"11-23": {"양치", "Fern", "성실"},
	"11-24": {"가막살나무", "Viburnum", "사랑은 죽음보다 강하다"},
	"11-25": {"개옻나무", "Rhus Continus", "현명"},
	"11-26": {"서양톱풀", "Yarrow", "지도"},
	"11-27": {"붉나무", "Phus", "신앙"},
	"11-28": {"과꽃", "China Aster", "추상"},
	"11-29": {"바카리스", "Baccharis", "개척"},
	"11-30": {"낙엽 마른 풀", "Dry Grasses", "새봄을 기다림"},
	"12-1":  {"쑥국화", "Tansy", "평화"},
	"12-2":  {"이끼", "Moss", "모성애"},
	"12-3":  {"라벤더", "Lavendar", "기대"},
	"12-4":  {"수영", "Rumex", "애정"},
	"12-5":  {"앰브로시아", "Ambrosia", "행복한 연애"},
	"12-6":  {"바위취", "Saxifraga", "절실한 사랑"},
	"12-7":  {"양치", "Fern", "신뢰"},
	"12-8":  {"갈대", "Reed", "깊은 애정"},
	"12-9":  {"국화", "Chrysanthemum", "고결"},
	"12-10": {"빨강 동백", "Camellia", "고결한 이성"},
	"12-11": {"단양쑥부쟁이", "Fig Marigold", "애국심"},
	"12-12": {"목화", "Cotton Plant", "우수"},
	"12-13": {"자홍색 국화", "Chrysanthemum", "사랑"},
	"12-14": {"소나무", "Pine", "용감"},
	"12-15": {"서향", "Winter Daphne", "불멸"},
	"12-16": {"오리나무", "Alder", "장엄, 팔레놉시스"},
	"12-17": {"벚꽃난", "Honey-Plant", "동감"},
	"12-18": {"세이지", "Sage", "가정의 덕"},
	"12-19": {"스노 플레이크", "Snow Flake", "아름다움"},
	"12-20": {"파인애플", "Pineapple", "완전무결"},
	"12-21": {"박하", "Mint", "덕"},
	"12-22": {"백일홍", "Zinnia", "행복"},
	"12-23": {"플라타너스", "Platanus", "천재"},
	"12-24": {"겨우살이", "Loranthaceac", "강한 인내심"},
	"12-25": {"서양호랑가시나무", "Holly", "선견지명"},
	"12-26": {"크리스마스 로즈", "Christmas Rose", "추억"},
	"12-27": {"매화", "Prunus Mume", "맑은 마음"},
	"12-28": {"석류", "Pomegranate", "원숙미"},
	"12-29": {"꽈리", "Winter Cherry", "자연미"},
	"12-30": {"납매", "Carolina Allspice", "자애"},
	"12-31": {"노송나무", "Chamaecyparis", "불멸"},
}
